### ISSUE TITLE
ReadMe states vacuum-card.js rather than shutter-row.js

### ISSUE THREAD

**Issue by masterfish1** [berrywhite96/lovelace-shutter-row#1]
Just a minor point but in the ReadMe, in the Manual installation section, all the references are to vacuum-card.js rather than shutter-row.js

**Comment by berrywhite96** [comment]
Ah thanks copy and paste has always the devil in the detail.

Thanks for the notice!

**Comment by foglietti** [comment]
Remember to change shutter-card.js to shutter-row.js in readme file.

**Comment by berrywhite96** [comment]
> Remember to change shutter-card.js to shutter-row.js in readme file.

Fixed thanks!
