### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mogim0gi** [berrywhite96/lovelace-shutter-row#10]
Hei, loving your work, this is my default card for windows for a while now.

There is one feature i would like you to implement if possible 👍 

As you can see my curtains opening to different directions, my feature suggestion allows inverting the starting point of the position slider (left or right) therefore it would correctly fill the curtain position.

in my example it would mean the right window slider starts from right to left and indicates a full blue line.

<img width="383" alt="image" src="https://user-images.githubusercontent.com/64898710/193351538-ed736408-442e-43b4-bcff-97dfbfb61410.png">

**Comment by berrywhite96** [comment]
Thanks, thats awesome to hear.

You mean like 0% is on the right and 100% on the left? So that the slider will be filled from right to left?

**Comment by mogim0gi** [comment]
like this:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/64898710/193363819-fd47bc2c-6be8-4a43-8809-06288c247b6a.png">

**Comment by berrywhite96** [comment]
Ok that seems useful, goes on the todo list.

**Comment by berrywhite96** [comment]
Released with [v0.3.0](https://github.com/berrywhite96/lovelace-shutter-row/releases/tag/v0.3.0).

**Comment by mogim0gi** [comment]
![Screenshot_20230304_002435_Chrome](https://user-images.githubusercontent.com/64898710/222842547-a68adfa1-8170-4f37-b1b7-36532db59df9.jpg)

Thanks!
