### ISSUE TITLE
Stop button no more working

### ISSUE THREAD

**Issue by dm82m** [berrywhite96/lovelace-shutter-row#12]
Hey,

since one of the last updates the stop button isn’t working. He is not activated if the shutter is going up or down. The button stays greyed out. I am running with inversion mode.

best
Dirk

**Comment by dm82m** [comment]
just tested and the behaviour is the same with default inversion mode.

**Comment by berrywhite96** [comment]
There is an extra config attribute since v0.2.1 for it.

**Comment by dm82m** [comment]
@berrywhite96 mentioning you as I am not sure if you get notifications on closed issues

**Comment by dm82m** [comment]
Ah sorry, was not seeing that one. Will read and provide my details.
