### ISSUE TITLE
Improvements?

### ISSUE THREAD

**Issue by SanderM2** [berrywhite96/lovelace-shutter-row#13]
1. I'm used to the HA default cover card which includes an UP and DOWN arrow. Your card displays a circumflex symbol (and one upside-down) which is much smaller to press on small smartphone. This is less handy for me and is holding me back for now.
I myself would prefer the default UP and DOWN arrow or an equivalent.
Picture:
![pic1](https://user-images.githubusercontent.com/24764180/194334080-48695bc3-6138-4927-8d13-920609a60885.jpg)

2. I also noticed that your card does not have a on mouse hover action like the default HA cover card has.
(It doesn't color the background of the hovered item and no popup is shown. 
Picture:
![pic2](https://user-images.githubusercontent.com/24764180/194334086-9fc326a2-d91e-4266-9ba3-01818fdc1242.jpg)

3. With the default HA cover card you get an UP or DOWN arrow while the cover is running. This arrow indicates in which direction the cover is currently running. I'm missing this feature in your card?
Picture:
![pic3](https://user-images.githubusercontent.com/24764180/194334089-ca1b72ea-2aab-4d90-b34d-9a0f706274ac.jpg)
![pic4](https://user-images.githubusercontent.com/24764180/194334092-07808bd7-4fde-4d86-afe8-d751a90f3f19.jpg)

Finally: I wonder if you would be interested in supporting these ( https://github.com/queimadus/cover-icon-element ) icons?
They included an UP/DOWN arrow (see point 3 above) and they also have 5 different icons which should be shown depending on the current position of the cover.

**Comment by SanderM2** [comment]
I changed all icons (opening, closing, and different icons for positions <25%, <50% and <75%) + changed icons for up/stop/down. My modified version can be found here: https://raw.githubusercontent.com/SanderM2/lovelace-shutter-row/main/shutter-row.js

I'm not sure if this is something you would like to adapt to your version? If not, I'll have to continue with a custom modified version instead.

But these icons can probably easily be made adjustable from config?

**Comment by berrywhite96** [comment]
First thanks for the suggestions!

> 1. I'm used to the HA default cover card which includes an UP and DOWN arrow. Your card displays a circumflex symbol (and one upside-down) which is much smaller to press on small smartphone. This is less handy for me and is holding me back for now.
>    I myself would prefer the default UP and DOWN arrow or an equivalent.

These aren't circumflex symbols. If you go into the source code you will see these are just different direction icons, because I just don't want to copy paste the vanilla cover card (I know it's very similar, but at least it's something).

The symbols aren't smaller if you can see in the picture below.
![d](https://user-images.githubusercontent.com/24818127/194380334-e4046c98-e092-41ba-9179-f183945c80c0.png)

> 2. I also noticed that your card does not have a on mouse hover action like the default HA cover card has.
>    (It doesn't color the background of the hovered item and no popup is shown.

Hovers are nice, this is something I could add in the future.

> 3. With the default HA cover card you get an UP or DOWN arrow while the cover is running. This arrow indicates in which direction the cover is currently running. I'm missing this feature in your card?
>
> Finally: I wonder if you would be interested in supporting these ( https://github.com/queimadus/cover-icon-element ) icons? They included an UP/DOWN arrow (see point 3 above) and they also have 5 different icons which should be shown depending on the current position of the cover.

These icons look nice, but the repo owner didn't add a license to the repo so I have no right to use these.

> But these icons can probably easily be made adjustable from config?

I see no point to add customizable dynamic icons, the entity icon should be enough.

**Comment by berrywhite96** [comment]
> I also like suggestion 3, as the mdi icon set is sorely missing different cover states. Are you sure you need a license in this case? The cover-icon-elemt icons are simple (and obvious) modifications of the standard mdi icons and therefore should have the same license IMHO.

No, I am not that into legal. But normally you push a license file into your repo, I don't know how it behave if you don't.

**Comment by jhmeier** [comment]
> I changed all icons (opening, closing, and different icons for positions <25%, <50% and <75%) + changed icons for up/stop/down. My modified version can be found here: https://raw.githubusercontent.com/SanderM2/lovelace-shutter-row/main/shutter-row.js
> 
> I'm not sure if this is something you would like to adapt to your version? If not, I'll have to continue with a custom modified version instead.
> 
> But these icons can probably easily be made adjustable from config?

Hi. I installed shutter row with HACS and replaced the js File with yours -  unfortunately even after a restart the icons don't change. Is their anything else that I need to do?
Thanks

**Comment by berrywhite96** [comment]
Released with [v0.3.0](https://github.com/berrywhite96/lovelace-shutter-row/releases/tag/v0.3.0).
