### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by rfnovo** [berrywhite96/lovelace-shutter-row#14]
Great project! HA is really missing a good Cover/Shutter card!

Couple suggestions:
- Add option to enable/disable the slide bar
- Add option to make it nested inside other cards, like Entities card:
![image](https://user-images.githubusercontent.com/11941836/194576471-253ba1ef-af16-4208-8db5-e31ee3a9bb8a.png)

**Comment by berrywhite96** [comment]
Thanks!

Searching for a long time now to check if card is nested, but didn't found anything. An extra config attribute would annoy me a bit, so I want to avoid it if possible.

**Comment by rfnovo** [comment]
> Thanks!
> 
> Searching for a long time now to check if card is nested, but didn't found anything. An extra config attribute would annoy me a bit, so I want to avoid it if possible.

Found a solution to nest the card:
  - type: custom:shutter-row
    entity: cover.custom_blind
    name: Custom Blind
    style: |
      ha-card {
        box-shadow: none;
        margin: -16px;
      }

![image](https://user-images.githubusercontent.com/11941836/194729189-d64317d4-e427-4b21-bb55-0739cf0a0a8e.png)

**Comment by berrywhite96** [comment]
> Couple suggestions:
> 
> * Add option to enable/disable the slide bar

So if you disable the slider bar, the current position state disappears also? I mean otherwise it would not make sense, because the whole space on the left from the state label isn't used.

**Comment by berrywhite96** [comment]
Released with [v0.3.0](https://github.com/berrywhite96/lovelace-shutter-row/releases/tag/v0.3.0).
