### ISSUE TITLE
state_color problem

### ISSUE THREAD

**Issue by miguelpucela** [berrywhite96/lovelace-shutter-row#15]
Thank you for this great card!

The issue I've found is the next:

When I set the position of a shutter different from 0, and state_color is set to true, the icon is yellow indefinitely.
Only if position is 0 the icon returns to blue.

**Comment by miguelpucela** [comment]
Ah, ok. I understood that active mean that the shutter was moving.

Then, there's no issue about that.

**Comment by maorcc** [comment]
@berrywhite96, I also understood at first that "active" means that the shutter is either currently opening or closing. I had to look at the source code to understand what "active" means "not closed".  

I suggest modifying the README.md text to say, "Enables icon coloring if the shutter is not fully closed"
