### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by kroon040** [berrywhite96/lovelace-shutter-row#16]
Hi,

Is it possible to add text  besides de value. Now it says 70%. I use my shutters on a ventilation postition, and it says that 12%, and it should be nice to set there 12% Open. So it should be nice to add Open besides that value

regards Richard

**Comment by berrywhite96** [comment]
Sorry, I thought I already answered here.

I worked the last weeks on the template support for card title and the position value. Now I am finally ready, 9a2a3c2f66c5d3191fda0af37b68f08915d01c37 contains the feature which will be included in the next minor version.

**Comment by berrywhite96** [comment]
Released with [v0.3.0](https://github.com/berrywhite96/lovelace-shutter-row/releases/tag/v0.3.0).
