### ISSUE TITLE
Adding Multiple in one card

### ISSUE THREAD

**Issue by markusheinen** [berrywhite96/lovelace-shutter-row#17]
Hey, first of all thanks for creating this card - love it... 
I looked into card mod to make the padding etc. smaller, but what I would love to have is to add multiple shutters to one card, that they are all listing below and like we have for switches, that it would be possible to close / open all shutters within one card, would that be possible?

**Comment by berrywhite96** [comment]
There is an `group` feature coming for the next version, where you could put all of your covers into a entities card and enable `group` on all entities.

I pushed a few days back a rc for 0.3.0 with this feature, you could try it from the dev branches.

**Comment by berrywhite96** [comment]
Released with [v0.3.0](https://github.com/berrywhite96/lovelace-shutter-row/releases/tag/v0.3.0).
