### ISSUE TITLE
Entity's state not updated on card while shutter is in motion

### ISSUE THREAD

**Issue by maorcc** [berrywhite96/lovelace-shutter-row#19]
While the shutter is moving, either opening or closing, the status text does not reflect the current entity state which is either "opening" or "closing".

For example, if the shutter is closed, the card shows the word "Closed", then when _open_ button is pressed, the card is still showing "Closed" text while the shutter is in motion.  The expected status text on the card in this case should be "Opening".

**Comment by berrywhite96** [comment]
Seems like your cover entity doesn't report any `current_position` in the attributes.

The card just displays the current position, or if it's fully closed or opened.

**Comment by maorcc** [comment]
I'm using the popular Shelly 2.5 x1 which does not update the `current_position` attribute while in motion, but it does set the entity's state to "Opening" or "Closing" while in motion.

**Comment by berrywhite96** [comment]
Ah okay, this is definitely something for the next release. In general I need to check for supported features at specific points.

**Comment by witooski** [comment]
Hi @berrywhite96, I have exactly the same issue. I'm using Aqara Shade Driver E1 (https://community.home-assistant.io/t/aqara-roller-shade-driver-e1/390739) and experience the same case as @maorcc. However, I was thinking maybe you could add simple "Running" state (just word) when the shutter is either closing or opening - just like the icon with down or up arrow shows up, while the shutter is moving.

Thanks a lot for your great work!

**Comment by berrywhite96** [comment]
> Hi @berrywhite96, I have exactly the same issue. I'm using Aqara Shade Driver E1 (https://community.home-assistant.io/t/aqara-roller-shade-driver-e1/390739) and experience the same case as @maorcc. However, I was thinking maybe you could add simple "Running" state (just word) when the shutter is either closing or opening - just like the icon with down or up arrow shows up, while the shutter is moving.
> 
> Thanks a lot for your great work!

There won't be any more features, just keep the card running. But thanks!

**Comment by maorcc** [comment]
Thanks @berrywhite96 for maintaining this card and keeping it running. 
I suggest writing in the README.md that there won't be any more features.
