### ISSUE TITLE
Error downloading from HACS

### ISSUE THREAD

**Issue by foglietti** [berrywhite96/lovelace-shutter-row#2]
I get next error when trying to download the card from HACS:

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:836 
Integration: HACS (documentation, issues) 
First occurred: 16:51:07 (1 occurrences) 
Last logged: 16:51:07

<Plugin berrywhite96/lovelace-shutter-row> No assets found for release 'tags/v0.1.1'

**Comment by berrywhite96** [comment]
I am currently not at home so it's really difficult to debug. Can you try again? The asset is now online.

**Comment by foglietti** [comment]
I have restarted Home Assistant and the problem persists.
I will try again later at home or download it manually.

Thanks.

**Comment by joostvkempen** [comment]
I've got the same issue, seems to be related to latest release. When choosing 'main' or 0.1.0 from HACS it will work. 0.1.1 does not work and also updating from 0.1.0 to 0.1.1 does not work. Maybe HACS requires something specific while versioning?

**Comment by berrywhite96** [comment]
> I've got the same issue, seems to be related to latest release. When choosing 'main' or 0.1.0 from HACS it will work. 0.1.1 does not work and also updating from 0.1.0 to 0.1.1 does not work. Maybe HACS requires something specific while versioning?

Still doesn't know why it just didn't work. I moved the compiled JS file from dist/ to root, changed the hacs.json and pushed a new v0.1.2 version. For me it's now working, please let me know if it works for you too @foglietti @joostvkempen.

It's my first Lovelace card so HACS and the mechanics behind it are new to me.

**Comment by joostvkempen** [comment]
works for me! updated with success to 0.1.2 and card is working! Tnx @berrywhite96

**Comment by foglietti** [comment]
For me also works. Thanks for your time @berrywhite96
