### ISSUE TITLE
Icon do's not update

### ISSUE THREAD

**Issue by SirGarnet** [berrywhite96/lovelace-shutter-row#24]
I would like to use the card for my windows, shutters and blinds, but the icon is alway the same. I've changed it in the entity, everything else (normal entity card, ...) updates the icon correctly.

System:
Home Assistant 2023.3.5
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230309.1 - latest

**Comment by berrywhite96** [comment]
Please check if you are on 0.3.3.

1. Call HA on desktop PC in Chrome
2. Press F12 and click on `Console`
3. There should be a yellow log entry with the loaded shutter row version.

**Comment by SirGarnet** [comment]
Yes there is the mentioned entry, I installed it via HACS the day I've opened this issue, so it should be up to date.

It is not a problem with a fixed set icon for an entity. If you change the device type (shutter / blind / door ...) it will use an other icon for the entity. But this icon is not shown in lovlace-shutter-row but when it's added as a normal entity.

**Comment by berrywhite96** [comment]
Device class icons are currently not supported, only if you set an custom icon for this entity you can change the icon.

**Comment by KennethLavrsen** [comment]
I would love to see this component use the default icons. There are so many covers and HA has becomes good at showing icons that reflect the state (open vs closed). You lose that when you set an icon yourself. I use this component for Venetian Blinds and the "Blinds" icons are much better at reflecting what it is than the roller shade icon that the component is locked on

**Comment by berrywhite96** [comment]
There won't be any more features, just keep the project running.

**Comment by KennethLavrsen** [comment]
That is OK. Berry. Thanks for keeping it running.
