### ISSUE TITLE
Popup HA onclick on card

### ISSUE THREAD

**Issue by bouboun59** [berrywhite96/lovelace-shutter-row#28]
Hi team,

when I click on a card with your plugin, the popup ha is displaying.
It's possible to desactive this.
Example :
<img width="699" alt="Capture d’écran 2023-09-13 à 19 38 22" src="https://github.com/berrywhite96/lovelace-shutter-row/assets/46579815/2a42d8f7-8d03-44dd-a508-2ac73c86af13">

**Comment by berrywhite96** [comment]
No, this isn't possible. Features won't be added anymore as I am putting my free time into a new HA card.
