### ISSUE TITLE
Slider position slider no longer working correctly in newer HA systems

### ISSUE THREAD

**Issue by SanderM2** [berrywhite96/lovelace-shutter-row#29]
Normally when you start sliding the slider, to change the cover position, it will show the position before you let lose your mouse (or finger in case of touch screen). This is no longer happening since on of the previous HA updates. It's an issue I'm facing for a couple months already.

Hasn't anyone noticed this before? Or didn't anyone care about it?

Because of this issue it's no longer possible to set my covers to for example 75% from the first try. I have to estimate where 75% is and adjust multiple times...

**Comment by SanderM2** [comment]
Also, normally when just overing over the slider it shows a tooltip with it's percentage (works on every entity in HA except the ones using this shutter row card.)

**Comment by berrywhite96** [comment]
Just pushed a potential v0.3.6 in dev which fixes the missing tooltip. A second pair of eyes which tests this fix and version would be nice.
