### ISSUE TITLE
Latest version (v.0.1.2) installed through HACS not showing up in the UI editor—even after HA reboot

### ISSUE THREAD

**Issue by convicte** [berrywhite96/lovelace-shutter-row#4]
![image](https://user-images.githubusercontent.com/78666770/187927979-4509d624-f49a-4f63-aed3-8cfdda189b25.png)

This said, works just fine from YAML editor:

![image](https://user-images.githubusercontent.com/78666770/187928417-adf9afc2-daff-40e8-92ca-84f3ff114df8.png)

The UI configuration in the YAML custom card is greyed out as well.

**Comment by berrywhite96** [comment]
Currently the UI configuration is not supported, but is planned.

**Comment by convicte** [comment]
That is absolutely OK, but then the README probably needs an adjustment, since it points to the UI configuration as standard.

![image](https://user-images.githubusercontent.com/78666770/188081473-562f5323-242c-4a80-9501-502b1ab27502.png)

**Comment by convicte** [comment]
Upon publishing my response, I realized you are referring to the frontend of HACS and not frontend for UI configuration.

Sorry for the confusion!
