### ISSUE TITLE
Invert slider

### ISSUE THREAD

**Issue by dm82m** [berrywhite96/lovelace-shutter-row#5]
Is it possible to add a property to invert the slider. If the state is open I would expect the slider to be on the left end of the scale. If it is closed I would expect the slider on the ride side of the scale. Currently it’s the other way around and confuses me.

**Comment by berrywhite96** [comment]
`invert_position` does that literally for you.

**Comment by dm82m** [comment]
No, it just switches the open/closed states but the slider keeps the functionality as it was before.

**Comment by berrywhite96** [comment]
> No, it just switches the open/closed states but the slider keeps the functionality as it was before.

So you mean you want to e.g. set 20% and the cover position is set to 80%?

**Comment by dm82m** [comment]
![34889DB9-F363-4AD7-BC58-72F41BD0DB4E](https://user-images.githubusercontent.com/736311/187988850-bf6aafd8-ddf0-4427-a876-797626a6f2cc.jpeg)

both are open. First one uses invert_position. But I do not want to invert the state of open/closed. I want to invert the slide. So in case of Open the slider should be left side. In case of closed it should be right side.

**Comment by dm82m** [comment]
> > No, it just switches the open/closed states but the slider keeps the functionality as it was before.
> 
> So you mean you want to e.g. set 20% and the cover position is set to 80%?

Maybe yes. But maybe this is also only some knots in my head. But asked my wife and she had the same desire 🥳

**Comment by berrywhite96** [comment]
> ![34889DB9-F363-4AD7-BC58-72F41BD0DB4E](https://user-images.githubusercontent.com/736311/187988850-bf6aafd8-ddf0-4427-a876-797626a6f2cc.jpeg)
> 
> both are open. First one uses invert_position. But I do not want to invert the state of open/closed. I want to invert the slide. So in case of Open the slider should be left side. In case of closed it should be right side.

Ahh okay the funny thing is all of my covers are set up this way. My covers have a attribute called `invert_cover` which I set to `true`. So I have exactly the behavior you want.

Atm I don't know what makes more sense:
- leave it that way
- invert also the functionality, so state = (100 - new_state) % 100
- offer a new attribute so everybody can do what they want

**Comment by berrywhite96** [comment]
Ah okay I thought this a common option. So it will be option 3 then, something for my todo list.

**Comment by berrywhite96** [comment]
Implemented with [v0.2.0 release](https://github.com/berrywhite96/lovelace-shutter-row/releases/tag/v0.2.0).
