### ISSUE TITLE
Castom services for full open/close curtain.

### ISSUE THREAD

**Issue by 1iverea9er** [berrywhite96/lovelace-shutter-row#6]
Hi!
This will be a very popular card. 
However, I can't fix one problem for myself with it. The fact is that my curtains are controlled only by the position tool. The standard full open/close buttons do not work. Curtains are integrated via Local Taya and probably that's why they don't work quite correctly. However, this would not be a problem if you expanded the settings of your card with the ability to assign custom services for full closure/opening.

**Comment by berrywhite96** [comment]
Thanks!
This is also on my list, but probably one of the last things I will do.

**Comment by berrywhite96** [comment]
Implemented with [v0.2.0 release](https://github.com/berrywhite96/lovelace-shutter-row/releases/tag/v0.2.0).
