### ISSUE TITLE
Extra padding

### ISSUE THREAD

**Issue by papadi** [berrywhite96/lovelace-shutter-row#9]
Any idea why there's extra padding for this card specifically?
![image](https://user-images.githubusercontent.com/3359377/190331998-a3dcb60e-4a62-4dff-92fe-5cc84560b05b.png)

**Comment by berrywhite96** [comment]
This isn't an extra padding, it's the normal padding from the card. As far as I know it's not possible to make a custom card which is compatible to be standalone and also to be a part of an `entities` card.

If you know a card which does this without using a vanilla card just let me know.

**Comment by SanderM2** [comment]
Using card_mod and a style like this you can make it smaller:

```
    style: |
      div.card-row { height: 25px }
      ha-card {
        box-shadow: none;
      }
```

**Comment by berrywhite96** [comment]
Same as #7 .
